Justinwong98/rpc blockchain get mempool entry
JellyfishSDK/jellyfish pull request #1281
Opened 2022-03-29 04:00 UTC by JustinWong98

#### What this PR does / why we need it:

/kind feature

#### Which issue(s) does this PR fixes?:
Implemented type for RPC: https://github.com/DeFiCh/jellyfish/issues/48
-  blockchain.getMempoolEntry()

#### Additional comments?:

2022-03-29 09:21 UTC, canonbrother commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +  it('should getMempoolEntry and return MempoolTx', async () => {
try test with invalid txid

2022-03-30 03:39 UTC, fuxingloh commented
<img width="916" alt="image" src="https://user-images.githubusercontent.com/4266087/160746705-e57ce616-3c30-443e-9e14-f7baac7cb562.png">


And retitle your PR to follow: https://github.com/DeFiCh/jellyfish/blob/main/.github/labeler.yml

2022-03-30 04:01 UTC, ivan-zynesis commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +      expect(mempoolEntry.vsize instanceof BigNumber).toStrictEqual(true)
Minor syntax suggestion, thinking 
```
expect(mempoolEntry).toStrictEqual({
  vsize: expect.any(BigNumber)
  ...
})
```
will be cleaner

2022-03-30 10:15 UTC, eli-lim requested changes

2022-03-30 10:15 UTC, eli-lim commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +      .rejects.toThrow(invalidTxIdErr)
Can simplify by inlining the error msg
```suggestion
    await expect(client.blockchain.getMempoolEntry('6b1bac73bf8071e7edecef30081058f342ff35be12eb2dd3aa1d2ec4933ee798'))
      .rejects.toThrow(`RpcApiError: 'Transaction not in mempool', code: -5, method: getmempoolentry`)
```

2022-03-30 10:15 UTC, eli-lim commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +    await expect(client.blockchain.getMempoolEntry('invalidtxidstring')).rejects.toThrow(invalidtxidstring)
Can simplify by inlining the error msg

```suggestion
    await expect(client.blockchain.getMempoolEntry('invalidtxidstring'))
      .rejects.toThrow(`RpcApiError: 'parameter 1 must be of length 64 (not 17, for 'invalidtxidstring')', code: -8, method: getmempoolentry`)
```

2022-03-30 10:15 UTC, eli-lim commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   * @param {string} txId the transaction id
Add description aligned with https://github.com/DeFiCh/ain/blob/63452763fef6d4dc7adf9df8e371def8ecd80caf/src/rpc/blockchain.cpp#L711

```suggestion
   * Get mempool data for the given transaction
   * @param {string} txId the transaction id
```

2022-03-30 10:15 UTC, eli-lim commented on docs/node/CATEGORIES/01-blockchain.md
>  interface MempoolTx {
`MempoolTx` interface is already defined above. No need to redefine it.
Instead, add interface for calling

```typescript
interface blockchain {
  getMempoolEntry (txId: string): Promise<MempoolTx>
}
```

2022-03-31 04:02 UTC, ivan-zynesis approved these changes

2022-03-31 04:05 UTC, eli-lim approved these changes

2022-03-31 04:50 UTC, canonbrother approved these changes

2022-04-01 10:02 UTC, cwkang1998 submitted a review, later dismissed

2022-04-01 10:02 UTC, cwkang1998 commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +describe('getMempoolInfo', () => {
```suggestion
describe('getMempoolEntry', () => {
```

2022-04-04 01:37 UTC, JustinWong98 commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolEntry.test.ts
> +describe('getMempoolInfo', () => {
Ah, thanks for pointing this out!

2022-04-21 17:41 UTC, eli-lim approved these changes

2022-04-22 06:13 UTC, canonbrother approved these changes

2022-06-14 05:09 UTC, fuxingloh approved these changes

2022-06-14 05:09 UTC, merged