feat(jellyfish-api-core): add blockchain getMempoolDescendants RPC
JellyfishSDK/jellyfish pull request #1404
Opened 2022-04-28 07:26 UTC by chanyusiang

#### What this PR does / why we need it:
This PR implements blockchain.getMempoolDescendants() from ain

#### Which issue(s) does this PR fixes?:
Part of #48

#### Additional comments?:

2022-04-28 09:07 UTC, cwkang1998 requested changes

2022-04-28 12:18 UTC, jingyi2811 commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   * @param {string} txId the transaction id in mempool
Need a break line between the comment and the first line that consist of @param

2022-04-28 12:19 UTC, jingyi2811 commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   * @param {string} txId the transaction id in mempool
```suggestion
   * @param {string} txId the transaction id
```
like how you write in https://github.com/JellyfishSDK/jellyfish/pull/1404/files#diff-401e60eaa7898f5ac9e4d982fcf34c68a2cd450a7a3c372d8243827ba6189c5bR239

2022-04-28 12:48 UTC, jingyi2811 commented
What happened if you passed in txid that the length is not 64?

2022-04-28 12:49 UTC, jingyi2811 commented on docs/node/CATEGORIES/01-blockchain.md
> +Get all in-mempool descendants if txId is in mempool as string[] if verbose is false else as json object.
The text here should be the same as the one you wrote in your RPC file

2022-04-28 12:52 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolDescendants.test.ts
> +      expect(mempoolEntry.length).toBeGreaterThan(0)
Maybe can check every element whether it has length = 64 or not

2022-04-29 04:05 UTC, chanyusiang commented on packages/jellyfish-api-core/__tests__/category/blockchain/getMempoolDescendants.test.ts
> +    }, 10000)
I need `waitForExpect` to ensure `mempoolEntry` is not empty though

2023-01-19 07:19 UTC, closed without merging