feat(jellyfish-api-core): Asymmetric pool swap fee
JellyfishSDK/jellyfish pull request #1577
Opened 2022-06-22 04:32 UTC by chanakasameera

#### What this PR does / why we need it:
https://github.com/DeFiCh/ain/pull/1354

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2022-06-30 03:55 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/setGov.test.ts
> +    // must wait until block count reaches fort canning gardens height
```suggestion
    // must wait until block count reaches fort canning spring height
```

2022-06-30 04:24 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/poolpair/poolswap.test.ts
> +  it('should poolSwap DFI to CAT - Token a fee direction in', async () => {
```suggestion
  it('should poolSwap DFI to CAT - Token A fee direction in', async () => {
```

2022-06-30 04:36 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/poolpair/poolswap.test.ts
> +    await testSwap(poolPairBefore, 'DFI', 'CAT', new BigNumber(0), new BigNumber(0))
feels like too much cognitive complexity inside this function. makes it harder to review. Can we dissect and put the test conditions inside each test. you can use a common function to do swapping, but let's put the final result checking inside the test case.

2022-06-30 04:37 UTC, surangap commented on packages/testcontainers/src/containers/RegTestContainer/index.ts
> +      '-fortcanninggardensheight=13'
```suggestion
      '-fortcanningspringheight=13'
```

2022-06-30 04:37 UTC, surangap requested changes
https://github.com/JellyfishSDK/jellyfish/pull/1577/files#r910597561

2022-07-01 03:24 UTC, surangap submitted a review, later dismissed

2022-07-01 04:29 UTC, fuxingloh commented
Conflicts on:

`packages/jellyfish-api-core/__tests__/category/masternode/setGov.test.ts`

2022-07-01 04:37 UTC, canonbrother reviewed
heyy.. question... 
what's the diff of 
```
[`v0/poolpairs/${ppTokenID}/token_a_fee_pct`]: '0.05'
```
with 
```
[`v0/poolpairs/${ppTokenID}/token_a_fee_direction`]: 'both'
```
??

2022-07-01 05:19 UTC, surangap commented
> heyy.. question... what's the diff of
> 
> ```
> [`v0/poolpairs/${ppTokenID}/token_a_fee_pct`]: '0.05'
> ```
> 
> with
> 
> ```
> [`v0/poolpairs/${ppTokenID}/token_a_fee_direction`]: 'both'
> ```
> 
> ??

`token_a_fee_pct ` - token a fee %
`token_a_fee_direction` - direction the fee applies, `in/ out/ both`

2022-07-01 06:03 UTC, canonbrother approved these changes

2022-07-01 06:04 UTC, canonbrother commented
> `token_a_fee_pct ` - token a fee %
> `token_a_fee_direction` - direction the fee applies, `in/ out/ both`

hmm.. feels like `token_a_fee_pct` and `token_a_fee_direction` are same use case..
btw.. the pr looks good to me

2022-07-01 07:07 UTC, fuxingloh approved these changes

2022-07-01 07:16 UTC, surangap approved these changes

2022-07-01 08:43 UTC, merged