Implement invalidate- and reconsiderBlock rpc with docs
JellyfishSDK/jellyfish pull request #860
Opened 2021-11-30 07:49 UTC by kresovic-milos

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Implemented RPC from #48:
1. blockchain.invalidateBlock
2. blockchain.reconsiderBlock

2021-11-30 12:36 UTC, surangap reviewed
for the codeclimate issue, @fuxingloh can help you to ignore it if refactoring to smaller sizes is not required.
other one haven't seen before. `Governance / DeFi Products (pull_request_target) ` is not in other recent PRs. Could be something new.
Can you also try adding `fixes` tag as below
`Fixes part of #48 `

2021-12-01 02:03 UTC, fuxingloh commented
> for the codeclimate issue, @fuxingloh can help you to ignore it if refactoring to smaller sizes is not required. other one haven't seen before. `Governance / DeFi Products (pull_request_target) ` is not in other recent PRs. Could be something new. Can you also try adding `fixes` tag as below `Fixes part of #48 `

I am going to remove that workflow altogether, we don't track it in the project anymore and no reason to do that now.

2021-12-02 05:49 UTC, surangap commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   *
```suggestion
```

2021-12-02 05:50 UTC, surangap commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   *
```suggestion
```

2021-12-02 05:55 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/blockchain/invalidateBlock.test.ts
> +  it('should resolve promise with null for existing hash', async () => {
Add a new test or update the existing one for the follojwing scenario.
go past block height `x` -> invalidate `x` -> check if new tip is on `x-1`

2021-12-02 06:03 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/blockchain/reconsiderBlock.test.ts
> +  it('should resolve promise with null for existing hash', async () => {
https://github.com/DeFiCh/jellyfish/pull/860/files#r760782109
Can `reconsiderblock` for the same block and check if it returns to the old original tip.

also can update this test to check the block height after reconsidering a valid block.

2021-12-02 06:04 UTC, surangap requested changes
few comments added.

2023-01-19 07:16 UTC, closed without merging